version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ${NODE_ENV:-production}.Dockerfile
    ports:
      - "${HOST_PORT:-80}:80"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ${NODE_ENV:-production} != production ? ./frontend:/app : /app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    expose:
      - "8321"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
