version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ${NODE_ENV:-production}.Dockerfile
    ports:
      - "3000:${FRONTEND_PORT:-80}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - VITE_API_URL=http://192.168.178.99:8321/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8321:8321"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
